<a href="https://colab.research.google.com/github/Uladnik/ml-zc-hw/blob/main/hw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
pd.__version__

'2.2.3'

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [ ]:
df.tail()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [ ]:
df['fuel_type'].nunique()

3

In [ ]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
df['fuel_efficiency_mpg'].max()

41.2

In [ ]:
df['horsepower'].median()

254.0

In [ ]:
df['horsepower'].fillna(df['horsepower'].mode()[0]).median()

252.0

In [ ]:
X = df[df['origin']=='Asia'][['vehicle_weight', 'model_year']].head(7).values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [ ]:
(np.linalg.inv(X.T @ X) @ X.T @ y).sum()

np.float64(0.36919696904925486)